### ISSUE TITLE
规避风控的建议

### ISSUE THREAD

**Issue by corvo007** [pcrbot/authMS#16]
目前的授权系统是一旦加入未授权群则立即退群，这可能导致：

- 被风控系统误判为加群发小广告后退群，以至于数日至永久都无法加入这个群

- 被系统施以更严厉的风控措施  

因此，建议：  

- 每天多个时段分批进行检查和退群

- 限速调用退群api，使之行为接近于人类

**Comment by var-mixer** [comment]
v0.2.1已新增，新加入的群均不会立刻退出以规避风控，此外退群发言与退群之间延迟增大
