### ISSUE TITLE
未识别已入群的Bug

### ISSUE THREAD

**Issue by Ericsheart** [pcrbot/authMS#17]
有时会出现机器人加入群后但是auth并未识别入群，也没有出现机器人入群时的提示语。
如果继续给该群充值，群名那一行显示的是 未知(Bot未加入此群)

**Comment by var-mixer** [comment]
群名是通过api获取的，群名提示位置是因为api没有返回，并非由本授权系统引起。此问题由来已久，在酷Q时代就有。
可以参看go-cqhttp的issue [#234](https://github.com/Mrs4s/go-cqhttp/issues/234)和[#301](https://github.com/Mrs4s/go-cqhttp/issues/301)
