### ISSUE TITLE
[建议]希望能够增加授权人与条件激活码

### ISSUE THREAD

**Issue by A-kirami** [pcrbot/authMS#18]
## 授权人

> 授权人为使用激活码激活Bot的用户
1. 查询授权的时候，返回的信息中增加授权人一项
2. 授权人可以私聊Bot，进行**群授权转移**(主人可设置转移CD时间)，**开关本群Bot**等功能
3. 授权人可以将自己的授权身份移交给他人

## 条件激活码

> 条件激活码即为激活码的使用增加条件
1. 能够设置激活码的使用次数，比如一个激活码可以多个群使用，每群仅可使用一次
2. 能够设置激活码的过期时间，过期之后自动销毁无法使用

**Comment by var-mixer** [comment]
有点复杂了，需要重构数据库，再鸽一阵子吧（

**Comment by var-mixer** [comment]
不再改了，咕咕咕，有BUG请反馈，尽量修。
