### ISSUE TITLE
[feature]希望能增加通知场景

### ISSUE THREAD

**Issue by corvo007** [pcrbot/authMS#19]
希望能在进行以下操作的时候通知操作对象：  
- 清除一个群的授权
- 为所有群变更授权
- 为单个群变更授权
- 在群之间转移授权
- 使用退群指令

**Comment by var-mixer** [comment]
1. 清除一个群的授权，按照默认配置了自动退群的话，会尝试退出群聊，并且在退群会提示原因。
2. 为所有群变更授权通知，涉及对所有群发消息，有两种办法：
    * 直接使用`util.notify_group()`，如果不加以限制，会导致短时间内发送大量消息，有风控的风险。
    * 使用广播，每发送一个群的消息后冷却0.5秒，会导致处理指令的总时间变得不可接收。
  因此不打算支持。
3. 下次更新支持。
4. 考虑转移授权的一般场景，旧群是机器人已加入的，而新群未加入，因此支持通知到原来的群，新群不会通知。（下次更新支持）
5. 退群时本来就会通知。早已有之。

**Comment by var-mixer** [comment]
已支持[4e99a68](https://github.com/pcrbot/authMS/commit/4e99a688cd4c39c616abf1da83addac6de627c3d)
