### ISSUE TITLE
使用群互联功能时读取不到数据库

### ISSUE THREAD

**Issue by timeance** [pcrbot/authMS#2]
使用了群互联功能，将数据设置成：`r'C:\Users\Administrator\Desktop\res\'`
结果抛出报错 `SyntaxError: EOL while scanning string literal`

注释是这样写的：
```
    # 互通数据库的目录,例如group.sqlite位置/root/database/group.sqlite
    # 此时便填写/root/database/即可
```
但实际上在 python 中，如果你的字符串最后一位是斜杠字符，那么即使字符串前面加了r，也是无法通过编译的

最后我把数据库的位置写成：`r'C:\Users\Administrator\Desktop\res\data_`
能顺利读取，只不过数据库的名字前面加上了`data_`

**Comment by var-mixer** [comment]
首先纠正一个问题，你打的是反斜杠而`\`不是斜杠`/`，在Windows系统中，斜杠`/`用于表示除，而反斜杠`\`用于表示目录。同时反斜杠`\`还用于表示转义字符。
我自己是在Linux上用的，但是以下测试都是在本地的Windows平台，我测试了几种写法，这是我的配置信息：
```
    # 第一种，直接使用斜杠，正常
    DB_PATH = 'D:/Workspace/yoshinobot/'

    # 第二种，使用反斜杠并转义，正常
    DB_PATH = 'D:\\Workspace\\yoshinobot\\'

    # 第三种，使用双反斜杠并表示不转义，正常
    DB_PATH = r'D://Workspace//yoshinobot//'

    # 第四种，直接使用反斜杠，出现你所述的错误
    DB_PATH = 'D:\Workspace\yoshinobot\'

    # 第五种，使用反斜杠并表示不转义，出现你所述的错误
    DB_PATH = r'D:\Workspace\yoshinobot\'
```
所以推荐使用斜杠而非反斜杠
