### ISSUE TITLE
无法启动，会报错

### ISSUE THREAD

**Issue by sugar-zero** [pcrbot/authMS#9]
已经根据readme操作过了，运行时会报错
![image](https://user-images.githubusercontent.com/32754222/92415516-dbe22300-f18b-11ea-977d-9f58e9d2b9eb.png)
![image](https://user-images.githubusercontent.com/32754222/92415527-e56b8b00-f18b-11ea-92f1-70913883610b.png)

**Comment by var-mixer** [comment]
您好，README说的是“替换”，既然替换则一定有原先的文件才可替换。请以`msghandler.py.example`中的内容替换原有的`mshhandler.py`，如果您找不到原先的`mshhandler.py`文件，我认为您不应当使用此插件。

**Comment by sugar-zero** [comment]
新clone下来的不存在msghandler.py如何替换？

**Comment by sugar-zero** [comment]
斯。。。。看错目录了原来
